name: Deploy

on:
  push:
    branches:
      - main
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive dist
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory dist \
            -cvf "$RUNNER_TEMP/dist.tar" \
            .

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ runner.temp }}/dist.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    permissions: 
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          timeout: 300000
          artifact_name: dist
